name: ocean_monitor
description: A Flutter app to monitor tides and fishing activities.

#publish_to: 'none' # Remove this line if you want to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.1.0
  fl_chart: ^0.50.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true